const ActionTypes = {
    USERNAME:'USERNAME',
    CURRENTUSER:'CURRENTUSER',
    ALLUSERS:'ALLUSERS',
    MESSAGES: 'MESSAGES',
    CHANGERECPUID: 'CHANGERECPUID',
    USERINFO : 'USERINFO',
    USERSIGNIN : 'USERSIGNIN',
    SENDMESSAGE : 'SENDMESSAGE',
    NEWMESSAGE : 'NEWMESSAGE',
    UPDATEREQOBJ : 'UPDATEREQOBJ'
}

export default ActionTypes;